### ISSUE TITLE
似乎订阅不会下发VMess+TCP+HTTP传输的Host参数[BUG]

### ISSUE THREAD

**Issue by GH6324** [wyx2685/v2board#1]
下面是我的传输配置，不知道是不是我的配置问题还是程序BUG......
{
  "header": {
    "type": "http",
    "request": {
      "version": "1.1",
      "method": "GET",
      "path": [
        "/"
      ],
      "headers": {
        "Host": [
          "www.example.com"
        ],
        "User-Agent": [
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537",
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/16.16299"
        ],
        "Accept-Encoding": [
          "gzip, deflate"
        ],
        "Connection": [
          "keep-alive"
        ],
        "Pragma": "no-cache"
      }
    },
    "response": {}
  }
}

**Comment by wyx2685** [comment]
属于上游既存BUG，这个分支只修VLESS了

**Comment by GH6324** [comment]
> 属于上游既存BUG，这个分支只修VLESS了

好的，谢谢
