### ISSUE TITLE
[Feature request]能否对原版v2b的 Clash 配置文件导入逻辑进行修改

### ISSUE THREAD

**Issue by vstar37** [wyx2685/v2board#101]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。
原版的V2B的 proxy-groups，默认导入所有proxies
etc:   - { name: 谷歌服务, type: select, icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Google.png, proxies: [节点选择]}
实际上这里的谷歌服务不仅会导入 “节点选择” ，还会导入v2b中挂载的全部节点。能否拆分这个导入逻辑，让每个proxy-groups导入的节点更加具体可控。

**Comment by rebecca554owen** [comment]
这是非通用需求，可以自行处理。
具体改一下下发的php即可。

**Comment by vstar37** [comment]
> 这是非通用需求，可以自行处理。 具体改一下下发的php即可。

您好，方便的话可以指明一下具体是那个php文件么

**Comment by rebecca554owen** [comment]
在 telegram 找我，@cumslut_site
