### ISSUE TITLE
[BUG]trojan+ws协议，无法下发V2rayN['path'] WebSocket路径信息

### ISSUE THREAD

**Issue by besnow** [wyx2685/v2board#105]
使用trojan+ws协议，无法下发给V2rayN $server['network_settings']['path'] 正确的WebSocket路径信息，['headers']['Host']正常下发，设置的参数为"path": "/ws?ed=2048"。其他客户端正常适配。

**Comment by wyx2685** [comment]
能不能直接发截图，描述不清不楚的

**Comment by besnow** [comment]
![屏幕截图 2024-05-11 082721](https://github.com/wyx2685/v2board/assets/62454149/a8e65d8b-1583-4ae9-9f76-ca2c290df045)
![屏幕截图 2024-05-11 083019](https://github.com/wyx2685/v2board/assets/62454149/7f1bd1c1-6bec-4a36-9759-cac73b4f3b08)
trojan+ws协议，[`path`]路径信息下发不了V2rayN

**Comment by wyx2685** [comment]
@besnow 请更新后测速

**Comment by besnow** [comment]
测试正常

**Comment by wyx2685** [comment]
感谢反馈
