### ISSUE TITLE
[BUG]关于已折抵的订单无法进行佣金下发

### ISSUE THREAD

**Issue by besnow** [wyx2685/v2board#107]
已折抵的订单（Order Status=4)无法进行佣金自动下发，也无法在订单过滤器中搜索和选取，无法手动确认佣金，也无显示。佣金状态(Commission status=0)会一直是待确认。只有去数据库中找到订单并修改佣金状态。

**Comment by wyx2685** [comment]
请更新测试

**Comment by besnow** [comment]
@wyx2685 测试正常
