### ISSUE TITLE
由于google recaptcha在大陆打不开，希望大佬能改成Cloudflare Turnstile验证

### ISSUE THREAD

**Issue by notetoday** [wyx2685/v2board#108]
由于google recaptcha在大陆打不开，希望大佬能改成Cloudflare Turnstile验证

**Comment by purelolly** [comment]
vendor/google/recaptcha/src/ReCaptcha/ReCaptcha.php
第52行 
public const SITE_VERIFY_URL = 'https://recaptcha.net/recaptcha/api/siteverify';
更改
public const SITE_VERIFY_URL = 'https://challenges.cloudflare.com/turnstile/v0/siteverify';

public/theme/default/assets/umi.js

第18161行
return "https://www.recaptcha.net/recaptcha/api.js?onload=".concat(x, "&render=explicit")
更改
return "https://challenges.cloudflare.com/turnstile/v0/api.js?onload=".concat(x, "&render=explicit")

**Comment by notetoday** [comment]
> vendor/google/recaptcha/src/ReCaptcha/ReCaptcha.php 第52行 public const SITE_VERIFY_URL = 'https://recaptcha.net/recaptcha/api/siteverify'; 更改 public const SITE_VERIFY_URL = 'https://challenges.cloudflare.com/turnstile/v0/siteverify';
> 
> public/theme/default/assets/umi.js
> 
> 第18161行 return "[https://www.google.com/recaptcha/api.js?onload=".concat(x](https://www.google.com/recaptcha/api.js?onload=%22.concat(x), "&render=explicit") 更改 return "[https://challenges.cloudflare.com/turnstile/v0/api.js?onload=".concat(x](https://challenges.cloudflare.com/turnstile/v0/api.js?onload=%22.concat(x), "&render=explicit")

谢谢大佬，请问Bob-Theme-Argon这个主题应该怎么改呢？

**Comment by imrelax** [comment]
期待提交到代码里面合并上去哦！！

**Comment by wyx2685** [comment]
@imrelax 这个修改需要部署安装完才能改，没法合

**Comment by imrelax** [comment]
那有没有可能在后台新作个功能。如比选项。选择谷歌还是cloudflare。
这样然后把cloudflare的功能单独做出来。这样可以把？

**Comment by wyx2685** [comment]
@imrelax 会做就做吧 我不会

**Comment by tools5** [comment]
@imrelax 你提交代码
