### ISSUE TITLE
[BUG] Reality H2和GRPC超时

### ISSUE THREAD

**Issue by Riverboat8865** [wyx2685/v2board#11]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
v1.7.4

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
在admin panel里面将传输协议从TCP改成grpc和h2(没有进一步填写SN设置), 小火箭均显示超时。节点重启XrayR也没有办法。是否是我甚至问题，还是其他问题？

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by wyx2685** [comment]
GRPC和H2不支持XTLS，请确保FLOW为空
其他的，能描述一下之前是什么协议，后端怎么配置的

**Comment by Riverboat8865** [comment]
我用的XTLS，后端inbound没有配置。是不是后端还需要专门写一个custom inbound把h2/grpc加上?

**Comment by wyx2685** [comment]
1.不支持xtls，flow必须为空
2.后端版本必须为[我改的XrayR](https://github.com/wyx2685/XrayR)最新版

**Comment by Riverboat8865** [comment]
好的，是我们的问题，我们之前在你的面板里面``XTLS流控算法``没有填空，感谢。

**Comment by Riverboat8865** [comment]
留空之后，FORXRAY可以，测速没问题，小火箭不行，超时，我发现小火箭并没``XTLS流控算法``的选项，可能小火箭不支持？

**Comment by wyx2685** [comment]
小火箭没测试过，目前没有设备，哈哈
