### ISSUE TITLE
[BUG]关于自定义邮件模板无法使用

### ISSUE THREAD

**Issue by besnow** [wyx2685/v2board#112]
当上传自定义邮件模板后，系统却依旧按照default模板进行发送。仅有一例外，那就是验证码的邮件会按照自定义模板发送，其余都是default模板。

**Comment by wyx2685** [comment]
@besnow 目前没有发现同样问题反馈

**Comment by besnow** [comment]
@wyx2685 草率了。
Lavarel 常见注意事项：

修改或者新增了邮件模板，需要：

php artisan view:clear

php artisan view:cache

重启 nginx
