### ISSUE TITLE
What is the difference between your v2board and your xboard?

### ISSUE THREAD

**Issue by MrVb0** [wyx2685/v2board#117]
I want to use your scripts
What is the difference between your v2board and your xboard?
Which one do you suggest?
What configuration do you suggest for them? (server OS / nginx version / **php version / mysql version / disabled php functions / php extensions** / ....)
Please advise me about the recommended installation method (for better efficiency).

**Comment by wyx2685** [comment]
@MrVb0 xboard is not mine

**Comment by MrVb0** [comment]
I meant these two : 
https://github.com/wyx2685/v2board/tree/master / https://github.com/wyx2685/v2board/tree/xboard
Anyway, I think your V2board is better
What configurations do you recommend for your V2board and also please advise on the suggested installation method, thanks

**Comment by wyx2685** [comment]
@MrVb0 i forgot to remove this branch Thank you for reminding
