### ISSUE TITLE
recommended configurations AND  installation method for WYX2685 V2Board

### ISSUE THREAD

**Issue by MrVb0** [wyx2685/v2board#118]
Hello, thank you for your good script
What configurations do you recommend for your V2board ? (server OS / nginx version **/ php version / mysql version / disabled php functions / php extensions /** ....) and also please advise on the suggested installation method, thanks

Please advise me about the recommended installation method and configurations  (for better efficiency).

**Comment by wyx2685** [comment]
@MrVb0 debian12/ubuntu22 then install nginx  php mariadb redis  using apt then I dont know
