### ISSUE TITLE
升级问题

### ISSUE THREAD

**Issue by TaneoX** [wyx2685/v2board#120]
大佬，用 sh update.sh 升级后还是原来的版本，没升级成功

**Comment by TaneoX** [comment]
还是直接覆盖就能升级，1.7.5

**Comment by wyx2685** [comment]
@TaneoX 请详细描述你在干嘛

**Comment by TaneoX** [comment]
就是大佬你的v2b版本升级，2月份直接下载压缩包搭建的想升级最新版，执行sh update.sh提示升级成功，但后台还是原来的版本

**Comment by wyx2685** [comment]
@TaneoX 非git安装不能用脚本升级
覆盖文件升级吧
