### ISSUE TITLE
[BUG]删除用户后，手机浏览后台序号对应邮箱错位，电脑打开则是正常的。

### ISSUE THREAD

**Issue by zhou1050** [wyx2685/v2board#123]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
v1.7.5

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------

手动删除用户后，在手机端访问网页序号对应的邮箱不对，电脑打开是正常的。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by zhou1050** [comment]
为什么要关闭

**Comment by wyx2685** [comment]
一个是问题看不明白
第二个是删用户导致的任何问题都不会处理

**Comment by zhou1050** [comment]
查看用户管理 序号1本来对应 123@qq.com 邮箱
用手机浏览后台  序号1对应 45484@qq.com
电脑打开后台显示是正常的，有什么办法解决吗？

**Comment by zhou1050** [comment]
后悔死了，删除了才想起来

**Comment by zhou1050** [comment]
不知道我表达清楚了没
