### ISSUE TITLE
[BUG]trojan ws，shadowrocket下发ws错误

### ISSUE THREAD

**Issue by besnow** [wyx2685/v2board#124]
协议是trojan ws，shadowrocket下发ws错误，path原本是/ws?ed=2560。回退至commit 50611d9a15ec001bd32fb23d74231a0ac6ca7c01无问题
--------
![photo_2024-07-14_10-54-56](https://github.com/user-attachments/assets/8ec38a1d-ab08-4c9d-9ffc-a1e481d91280)

**Comment by wyx2685** [comment]
@besnow 原本也是转义的，目前行为没有区别

**Comment by wyx2685** [comment]
请测试新版本

**Comment by besnow** [comment]
@wyx2685 测试trojan ws 在shadowrocket下发中正常，但测试 vless ws 在shadowrocket下发中依然呈现相同错误。

**Comment by wyx2685** [comment]
只能说垃圾软件笑死

**Comment by besnow** [comment]
测试commit 0ce17ac128fef907da38d2600af0e731122b79c9,  trojan+ws,trojan+grpc,vless+ws,vless+grpc四种方式的协议。目前shadowrocket测试正常。但在测试客户端passwall下发中呈现如下错误：
![屏幕截图 2024-07-17 112337](https://github.com/user-attachments/assets/fd10e200-74ba-4a01-836e-b86128e03c6f)
![屏幕截图 2024-07-17 112604](https://github.com/user-attachments/assets/700740a9-bf7f-4771-ad04-a2a9b67bd19d)
![屏幕截图 2024-07-17 112410](https://github.com/user-attachments/assets/c9a69c3f-74cb-425e-9d88-fb3784240825)
![屏幕截图 2024-07-17 112634](https://github.com/user-attachments/assets/34b36632-f075-4f56-b649-d80dc39a0a89)
![屏幕截图 2024-07-17 112434](https://github.com/user-attachments/assets/7acda1ba-c3d0-4db3-b88d-d22c3955cc3d)
![屏幕截图 2024-07-17 112710](https://github.com/user-attachments/assets/03a2eea7-e613-434e-aec7-4d99729e1ca0)
![屏幕截图 2024-07-17 112456](https://github.com/user-attachments/assets/4e803582-f793-40b1-89a5-a02b61abd54e)
![屏幕截图 2024-07-17 112810](https://github.com/user-attachments/assets/54318abd-75c0-4d9d-8389-7031b2f0a23c)

**Comment by besnow** [comment]
经测试commit 0fd6c0186262b460ca956a2b0230681c4829f690，在客户端passwall中，trojan+ws,trojan+grpc依然呈现错误下发，与之前上图一致，vless+ws正常。

**Comment by wyx2685** [comment]
我去看了passwall的代码，没有ws和grpc相关的处理，也就是trojan下发后默认只有TCP
这个只能等开发者解决

**Comment by besnow** [comment]
passwall才是辣鸡软件
