### ISSUE TITLE
[BUG]支付问题

### ISSUE THREAD

**Issue by zhou1050** [wyx2685/v2board#125]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
V1.7.5

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
在用户有余额的情况下支付金额计算逻辑有问题！

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

![image](https://github.com/user-attachments/assets/97ff8bd3-5a75-4a6f-8017-5f3a91d42e47)

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
![image](https://github.com/user-attachments/assets/3dca437f-dcdb-4cdd-893b-32255c7a524d)

**Comment by zhou1050** [comment]
支付时没有使用折扣

**Comment by zhou1050** [comment]
好像只有管理员账号会这样

**Comment by wyx2685** [comment]
看不懂，等个同类反馈吧
