### ISSUE TITLE
device_limit_mode

### ISSUE THREAD

**Issue by MrVb0** [wyx2685/v2board#128]
In the bootstrap/cache/config.php file, the device_limit_mode option is equal to 0, do you need any special changes or settings to use device_limit or speed_limit? Do we need to make this option equal to 1???

**Comment by wyx2685** [comment]
![Screenshot 2024-07-23 140602](https://github.com/user-attachments/assets/c75a24bd-64fc-4c8d-8911-e3b2a5538d01)

device_limit_mode = 0 , same IP on different nodes count multiple devices
device_limit_mode = 1 , same IP on different nodes count 1 devices
