### ISSUE TITLE
Device limit can only be used on Hysteria2 protocol

### ISSUE THREAD

**Issue by dziiofficialo0** [wyx2685/v2board#130]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
1.7.4
--------

Briefly describe the problem you are experiencing
Device limits can only be used on Hysteria2 protocol, Vmess-Shadowsocks-Trojan cannot use device limits. Thank you very much if you can help me fix it
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
![image](https://github.com/user-attachments/assets/c03e62bc-04a7-4b53-866f-e8d0bf1c0dc8)
![image](https://github.com/user-attachments/assets/93048d75-22d1-42c9-8c92-f0f8767b6c71)

--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by wyx2685** [comment]
@dziiofficialo0 need more information

**Comment by dziiofficialo0** [comment]
Currently, the limit_device function only works if the customer uses the Hysteria2 node, if the customer uses the Vmess, Shadowsocks or Trojan node, the device management page will report that there are no users. Although during this time customers are still using the Vmess-Shadowsocks or Trojan node.
I tried using the Hysteria2 button and when I used it, it returned the result that 1/2 of the device was being used. However, when changing to the Vmess-Shadowsocks or Trojan button, the result returned is 0/2 devices used.
That means I only see it return a result of 1/2 when the customer uses Hysteria2, and the remaining protocols, even if the customer uses it, still give a result of 0/2.

![image](https://github.com/user-attachments/assets/47b07d2d-c05a-4a9a-a8c7-b58bc4fe5dad)
![image](https://github.com/user-attachments/assets/968dc220-cce1-43dc-83c7-9eb90f07127b)

**Comment by wyx2685** [comment]
@dziiofficialo0 what backend server program you use? (xrayr/v2bx...)

**Comment by dziiofficialo0** [comment]
I use Progens by Dopaemon, will using v2bx fix this problem?

**Comment by wyx2685** [comment]
@dziiofficialo0 only modified xrayr/v2bx support device_limit

**Comment by wyx2685** [comment]
@dziiofficialo0 In public/asset/admin/umi.js all Chinese word written by unicode
It's quite difficult please try it urself

**Comment by dziiofficialo0** [comment]
yes i will try, thank you so much for taking the time to support me wish you all the best 💯
