### ISSUE TITLE
webman 添加到进程守护的疑问

### ISSUE THREAD

**Issue by zhoushao2018** [wyx2685/v2board#131]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
最新版

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
看到有个安装这个分支的教程https://github.com/vlesstop/xiaoV2b
说要添加webman 进程守护
php -c cli-php.ini webman.php start

这个是必须的嘛？有啥作用啊？
不添加到进程守护行不

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

**Comment by wyx2685** [comment]
@zhoushao2018 如果你看不懂教程请按原版搭建

**Comment by wyx2685** [comment]
确认php版本是8以上
执行./update.sh更新后重试

**Comment by alexallen1** [comment]
> 确认php版本是8以上 执行./update.sh更新后重试

你好，一個小問題。我看好像更新了有禮品卡
然後我進入www目錄 ./update.sh 執行後 沒禮品卡分頁~還是V1.7.5
請問是要點哪裡嗎~

**Comment by wyx2685** [comment]
@alexallen1 刷一下浏览器缓存
问问题进tg群问不要开issue
