### ISSUE TITLE
Hiddify & Sing-box (IOS) error while synchronizing server

### ISSUE THREAD

**Issue by dziiofficialo0** [wyx2685/v2board#132]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
1.7.4
--------

Briefly describe the problem you are experiencing
I encountered this problem when I synced the server to the sing-box app on IOS, however when I tried sing-box again on my android device everything worked fine, Hiddify has the same problem. Can you give me a solution to fix this problem?
--------

Screenshot of the reported error(Please do desensitization)
![IMG_20240730_063649](https://github.com/user-attachments/assets/c61a72db-7aca-4e3f-a9bc-4376d582b962)

![Screenshot_20240730-060429](https://github.com/user-attachments/assets/288d7ca3-8d8a-45be-8a33-80a071315f81)

--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by wyx2685** [comment]
this project doesn't support hiddify now

**Comment by dziiofficialo0** [comment]
What about sing-box? Can you help me fix the problem with singbox?

**Comment by wyx2685** [comment]
@dziiofficialo0 first time start singbox
your 1st proxy server outbound must be available
