### ISSUE TITLE
使用基于docker的PHP运行时会出现无法连接至数据库的情况

### ISSUE THREAD

**Issue by panyt0615** [wyx2685/v2board#134]
系统版本：Ubuntu 20.04 LTS (GNU/Linux 5.4.0-28-generic x86_64)
docker版本：27.1.1
MySQL版本：8.2.0
OpenResty版本：1.21.4.3-3-3-focal
php版本：7.4.33（8.3.8也试了）
一下为php已安装扩展
Core=7.4.33
date=7.4.33
libxml=7.4.33
openssl=7.4.33
pcre=7.4.33
sqlite3=7.4.33
zlib=7.4.33
ctype=7.4.33
curl=7.4.33
dom=20031129
fileinfo=7.4.33
filter=7.4.33
ftp=7.4.33
hash=7.4.33
iconv=7.4.33
json=7.4.33
mbstring=7.4.33
SPL=7.4.33
PDO=7.4.33
pdo_sqlite=7.4.33
session=7.4.33
posix=7.4.33
readline=7.4.33
Reflection=7.4.33
standard=7.4.33
SimpleXML=7.4.33
Phar=7.4.33
tokenizer=7.4.33
xml=7.4.33
xmlreader=7.4.33
xmlwriter=7.4.33
mysqlnd=mysqlnd 7.4.33
cgi-fcgi=7.4.33
mysqli=7.4.33
pcntl=7.4.33
redis=5.3.7
sodium=7.4.33
MySQL，OpenResty，PHP均部署在docker上
在使用安装脚本进行安装时，提示数据库连接失败  ，本人并没有发现有其他任何日志记录
关于数据库的地址，本人尝试了一下几种：
    容器地址
    127.0.0.1
    localhost
    服务器IP地址
    服务器域名
该问题在原项目和本项目上都有。

**Comment by wyx2685** [comment]
不应该去问docker嘛

**Comment by UGYnpU2nuB8QCFqDrsWZgmxMBp43WQ** [comment]
是因为pdo_mysql这个拓展没有安装导致的哦

**Comment by panyt0615** [comment]
> 是因为pdo_mysql这个拓展没有安装导致的哦（你用的是mysql或者mariadb吧）

感谢你的解答，我安装拓展后成功的安装了它但是登录后台时还是遇上了连接数据库的问题，我抓取了相关日志文件（做了脱敏处理）
[v2.log](https://github.com/user-attachments/files/16739043/v2.log)
我正在尝试解决环境上的问题

**Comment by UGYnpU2nuB8QCFqDrsWZgmxMBp43WQ** [comment]
我试着做了Docker Compose部署的方案
https://github.com/UGYnpU2nuB8QCFqDrsWZgmxMBp43WQ/v2board

**Comment by UGYnpU2nuB8QCFqDrsWZgmxMBp43WQ** [comment]
暂时稳定运行
