### ISSUE TITLE
[Feature request] Add support [Log Viewer]

### ISSUE THREAD

**Issue by GenzPN** [wyx2685/v2board#138]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。

I want this support [[Log Viewer]](https://log-viewer.opcodes.io/) 

This is a tool to check error when Laravel error

![image](https://github.com/user-attachments/assets/64a6d7cc-3408-4af4-84f7-ee230b60b34b)

**Comment by wyx2685** [comment]
v2board error log doesn't store as laravel.log file.
