### ISSUE TITLE
Table: v2_log Error Log 

### ISSUE THREAD

**Issue by Redshado0w** [wyx2685/v2board#139]
hi
thanks for any support 
 i see many error : 

tittle:
file_put_contents(/www/wwwroot/my site/storage/framework/cache/data/6a/05/6a05xxxdd96xxxxxxxxxxxxxxab): failed to open stream: No such file or directory

**Comment by Redshado0w** [comment]
any ideas ?

**Comment by wyx2685** [comment]
reinstall
