### ISSUE TITLE
[BUG] 更新到v2board的最新分支后，订阅链接无法读取

### ISSUE THREAD

**Issue by Riverboat8865** [wyx2685/v2board#14]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------

你最新的master分支

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------

更新后，小火箭刷新订阅，显示internal error，同样clash-verge显示500 internal error。
代开v2board的laravel log,显示如下：
没脱敏，编辑了

貌似数据库里面找不到节点，但是之前版本都可以，是不是因为新版改了short_id, 导致数据库database无法同步？

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by Riverboat8865** [comment]
通过手动在面板输入一个shortid,可以解决这个问题， 目前显示超时，是不是XrayR后端也需要更新，匹配short_id?

**Comment by wyx2685** [comment]
内容没脱敏，编辑一下
确实更新草率了，需要每个节点打开安全性配置点一下保存

**Comment by wyx2685** [comment]
https://github.com/wyx2685/v2board/commit/44f3c8138052824c082ec6c4819dc819eb8924e6
