### ISSUE TITLE
[BUG] 订阅管理中编辑订阅保存时会 403 不让保存

### ISSUE THREAD

**Issue by imJack6** [wyx2685/v2board#140]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
v1.7.5 fa23f30

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
rt，订阅管理中编辑订阅保存时会 403 不让保存

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![1ffd22658d039a7dc11a6a226426a18a](https://github.com/user-attachments/assets/651f1f07-edbc-44c4-b23b-e22cf3edc1dc)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![8451123a6063b5c6aa36079016048f6a](https://github.com/user-attachments/assets/8aed567a-aacc-44b4-8bea-a7d9d9e24d56)

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
无

**Comment by wyx2685** [comment]
先把宝塔删了再说吧

**Comment by imJack6** [comment]
> 先把宝塔删了再说吧

用的 1Panel + OpenResty

**Comment by wyx2685** [comment]
@imJack6 你得自己查面板导致的乱七八糟的权限问题

**Comment by imJack6** [comment]
> @imJack6 你得自己查面板导致的乱七八糟的权限问题

收到，不行我单独部署 OpenResty 吧
