### ISSUE TITLE
[BUG]Stripe ALL支付方式无法使用，报错500

### ISSUE THREAD

**Issue by forjustice** [wyx2685/v2board#143]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.5

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
使用了最新的[Stripe ALL的代码](https://github.com/wyx2685/v2board/commit/929430f93250a0ae87dafb25e888f30386f8cdaf)，调试STRIPE ALL 支付方式时，提交订单支付时报错500.

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by wyx2685** [comment]
@lufeiit

**Comment by lufeiit** [comment]
条件不足，无法判断，给出 nginx 伪静态配置，数据库 log 报错信息

**Comment by ussoou** [comment]
全新安装XiaoV2B，支付方式为alipay，log提示“The statement_descriptor parameter is not supported for the payment_method_type `card`. To continue supporting payment_method_type `card`, please pass in `statement_descriptor_suffix` or remove the `statement_descriptor` parameter altogether.”，添加suffix后，alipay支付方式正常；
支付方式为card，log提示“Missing required param: card.”

**Comment by forjustice** [comment]
增加如下伪静态后，在支付方式处填写cards可以正常跳转stripe，但填写alipay或者wechat_pay或者【alipay, wechat_pay, cards】，均跳转失败！（支付宝和微信支付已开通）
另外，如何支持向之前的Checkout文件可以自动的在一个页面让用户选择多种支付方式呢？

location ~ (/config/|/manage/|/webhook|/payment|/order|/theme/) {
try_files $uri $uri/ /index.php$is_args$query_string;
}

**Comment by lufeiit** [comment]
> 增加如下伪静态后，在支付方式处填写cards可以正常跳转stripe，但填写alipay或者wechat_pay或者【alipay, wechat_pay, cards】，均跳转失败！（支付宝和微信支付已开通） 另外，如何支持向之前的Checkout文件可以自动的在一个页面让用户选择多种支付方式呢？
> 
> location ~ (/config/|/manage/|/webhook|/payment|/order|/theme/) { try_files $uri $uri/ /index.php$is_args$query_string; }

可按照代码修改checkout代码即可，修改为Payment Intents API

确保stripe api及webhook的版本为最新，我测试的版本为2024-04-10，三种方式均正常，但首选需要你的账户支持

**Comment by lufeiit** [comment]
> 全新安装XiaoV2B，支付方式为alipay，log提示“The statement_descriptor parameter is not supported for the payment_method_type `card`. To continue supporting payment_method_type `card`, please pass in `statement_descriptor_suffix` or remove the `statement_descriptor` parameter altogether.”，添加suffix后，alipay支付方式正常； 支付方式为card，log提示“Missing required param: card.”

注意参数，
'payment_method' => [
                'label' => '支付方式',
                'description' => '请输入alipay, wechat_pay, cards',
                'type' => 'input',
            ]
建立是需要输入cards

**Comment by ussoou** [comment]
> > 全新安装XiaoV2B，支付方式为alipay，日志提示“Payment_method_type 不支持 statements_descriptor 参数`card`。如需继续支持 payment_method_type `card`，请传入`statement_descriptor_suffix`或全部删除该`statement_descriptor`参数”，添加后缀后，alipay支付方式正常；支付方式为card，日志提示“Missing required param: card.”
> 
> 注意参数， ' payment_method' => [ 'label' => '支付方式', 'description' => '请输入alipay, wechat_pay, cards', 'type' => 'input', ] 建立时需要输入cards

已测试，修改传入参数为 statement_descriptor_suffix 后，cards自动跳转checkout，alipay使用payment_intent_api，均正常，stripe需添加相关监听参数

**Comment by lufeiit** [comment]
> > > 全新安装XiaoV2B，支付方式为alipay，日志提示“Payment_method_type 不支持 statements_descriptor 参数`card`。如需继续支持 payment_method_type `card`，请传入`statement_descriptor_suffix`或全部删除该`statement_descriptor`参数”，添加后缀后，alipay支付方式正常；支付方式为card，日志提示“Missing required param: card.”
> > 
> > 
> > 注意参数， ' payment_method' => [ 'label' => '支付方式', 'description' => '请输入alipay, wechat_pay, cards', 'type' => 'input', ] 建立时需要输入cards
> 
> 已测试，修改传入参数为 statement_descriptor_suffix 后，cards自动跳转checkout，alipay使用payment_intent_api，均正常，stripe需添加相关监听参数

不清楚你的stripe设置，代码上不修改为statement_descriptor_suffix ，三种方式，我测试了5个不同的站点，均正常。原则上，cards、支付宝、微信需要设置不同的webhook，支付宝微信的监听方式相同，cards需监听checkout，这些监听参数具体看代码。还有你需要测试支付后回调是否正常，如不正常，请逐步调整你的nginx伪静态配置

**Comment by ussoou** [comment]
> > > > 全新安装XiaoV2B，支付方式为alipay，日志提示“Payment_method_type 不支持 statements_descriptor 参数`card`。如需继续支持 payment_method_type `card`，请传入`statement_descriptor_suffix`或全部删除该`statement_descriptor`参数”，添加后缀后，alipay支付方式正常；支付方式为card，日志提示“Missing required param: card.”
> > > 
> > > 
> > > 注意参数， ' payment_method' => [ 'label' => '支付方式', 'description' => '请输入alipay, wechat_pay, cards', 'type' => 'input', ] 建立时需要输入cards
> > 
> > 
> > 已测试，修改传入参数为 statement_descriptor_suffix 后，cards自动跳转checkout，alipay使用payment_intent_api，均正常，stripe需添加相关监听参数
> 
> 不清楚你的stripe设置，代码上不修改为statement_descriptor_suffix ，三种方式，我测试了5个不同的站点，均正常。原则上，cards、支付宝、微信需要设置不同的webhook，支付宝微信的监听方式相同，cards需监听checkout，这些监听参数具体看代码。还有你需要测试支付后回调是否正常，如不正常，请逐步调整你的nginx伪静态配置

stripe test&live模式cards/alipay支付回调均正常，我这里传入参数需要改为statement_descriptor_suffix，才能正常支付与回调；其他无任何问题，感谢您的辛勤付出~
