### ISSUE TITLE
[Feature request]更完善的双语 或 多语言支持

### ISSUE THREAD

**Issue by vstar37** [wyx2685/v2board#152]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。

目前v2b的多语言支持功能十分不完善，主要体现在：

-  无法根据用户系统语言  显示  相应语言配置
-  公告没做语言区分，没有像知识库一样的语言分类

望采纳，感谢开发。

**Comment by wyx2685** [comment]
I won't do this.
Just waiting someone else
