### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dziiofficialo0** [wyx2685/v2board#156]
在新版本中，我自定义了每个月的第一天作为客户流量重置日期。但它不起作用，它会在下个月为客户积累 GB。
之前效果很好，请问如何修复呢？
我非常感谢你

**Comment by smalllam** [comment]
@dziiofficialo0 队列

**Comment by dziiofficialo0** [comment]
> @dziiofficialo0 队列

![image](https://github.com/user-attachments/assets/27421ce5-d833-4a7a-86bb-a7c9767ab360)

**Comment by wyx2685** [comment]
请提供详细过程
如果不会中文请用英文
