### ISSUE TITLE
[BUG]邀请用户的奖励发放一直处于待生效

### ISSUE THREAD

**Issue by MrShellad** [wyx2685/v2board#16]
[BUG]邀请用户的奖励发放一直处于待生效，似乎是数据库操作出现问题

**Comment by wyx2685** [comment]
没看过这一块，尽量查一下日志，我只能研究研究

**Comment by wyx2685** [comment]
有出现相同问题的人，定位到是cron计划任务没有正确执行，非BUG，请自查。
