### ISSUE TITLE
[BUG]统计问题 

### ISSUE THREAD

**Issue by blackness3** [wyx2685/v2board#168]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
最新版本

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
已过期的用户，却显示正在使用并且面板上有流量消耗。
封禁用户或者重置token  流量归零也无效。测试添加订阅是添加不上的 但是面板上显示流量计数。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
流量归零的截图
![image](https://github.com/user-attachments/assets/91e7ca3b-28d3-4b63-ab9d-6b3e54fb4ddd)

3分钟后的截图

![image](https://github.com/user-attachments/assets/dc083cbc-d685-4182-b1ff-e67b276905bf)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by wyx2685** [comment]
关掉面板通信地址的cdn
打开节点日志等级到debug 获取详细日志

麻烦先自查

**Comment by blackness3** [comment]
> 关掉面板通信地址的cdn 打开节点日志等级到debug 获取详细日志
> 
> 麻烦先自查

感谢 已解决。
