### ISSUE TITLE
[BUG]增加导入订阅到Hiddify失败

### ISSUE THREAD

**Issue by forjustice** [wyx2685/v2board#169]
在20241105的【增加导入订阅到Hiddify】中，经测试，失败。
如下链接可供导入，请参考。
href: "hiddify://install-config?url=" + encodeURIComponent(e) + "&name=" + window.settings.title

**Comment by wyx2685** [comment]
@forjustice deprecated的格式不想加了，以后再说

**Comment by forjustice** [comment]
已修正，已测试功能正常。
