### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by Github-Aiko** [wyx2685/v2board#17]
Is it possible to add ip limit using node directly in the panel?

**Comment by wyx2685** [comment]
面板端下达单个节点的ip数量限制比较简单，但实际还需要节点后端来实现。
如果要做所有节点ip数限制，比较麻烦目前没有思路

**Comment by Github-Aiko** [comment]
Report IP of SSPANEL?

**Comment by Github-Aiko** [comment]
Hope Func comming soon

**Comment by tachikawa48** [comment]
Isn't that what XrayR's GlobalDeviceLimitConfig is for?
