### ISSUE TITLE
[BUG]流量重置问题

### ISSUE THREAD

**Issue by besnow** [wyx2685/v2board#170]
流量耗尽，重置流量后，流量没有归零，这是套餐统计前后情况。偶发。后端是 XiaoXrayR
![photo_2024-11-06_21-45-48](https://github.com/user-attachments/assets/f3e9e647-71d4-4311-a0ab-1bd8b37cc13a)
![photo_2024-11-06_21-46-08](https://github.com/user-attachments/assets/72677598-286e-488c-b787-a080223c17a5)

**Comment by wyx2685** [comment]
自查数据库记录
