### ISSUE TITLE
[优化请求] 充值订单的api以及数据库

### ISSUE THREAD

**Issue by xxg996** [wyx2685/v2board#171]
我目前对接的一款主题 展现订单时api回应 type=9，period=deposite，产品信息null 导致主题崩溃 并且 api回应不应该是这样
我与主题开发者沟通 这个问题要从根源解决 请xiao佬注意一下这个问题 (偷偷问一下 xiao佬是偷懒了吗～～)

**Comment by wyx2685** [comment]
我为啥要管别的主题

**Comment by wyx2685** [comment]
还有一个，问题应该从根源解决

目前问题根源是你在使用某主题时对接了错误的面板，你应该遵照该主题给的适用范围来使用

**Comment by xxg996** [comment]
抛开其他主题 其实我只是想让这个api响应信息更多...这样更好适配一些app或者
