### ISSUE TITLE
前端页面显示 500

### ISSUE THREAD

**Issue by caulfieldrnmt7** [wyx2685/v2board#172]
V2board 1.7.4 面板 迁移过来的

系统是 Contes
linux 5.14.0-474.el9.x86_64

Redis正常运行

尝试过
`chmod -R 755 ./`

![002](https://github.com/user-attachments/assets/99184b97-668c-4594-983b-8363a44337f3)

前端页面显示
500 | View [v2board.dashboard] not found.
![001](https://github.com/user-attachments/assets/f0e6c181-c27f-4508-a7de-440186916238)

storage/logs 内容如下

`[2024-11-15 06:32:11] local.ERROR: SQLSTATE[HY000] [2002] No such file or directory (SQL: insert into `v2_log` (`title`, `level`, `host`, `uri`, `method`, `ip`, `data`, `context`, `created_at`, `updated_at`) values (Connection refused, ERROR, http://localhost, /, GET, 127.0.0.1, [], {"exception":{"\u0000*\u0000message":"Connection refused","\u0000Exception\u0000string":"","\u0000*\u0000code":0,"\u0000*\u0000file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Redis\/Connectors\/PhpRedisConnector.php","\u0000*\u0000line":153,"\u0000Exception\u0000trace":[{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Redis\/Connectors\/PhpRedisConnector.php","line":153,"function":"connect","class":"Redis","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Redis\/Connectors\/PhpRedisConnector.php","line":84,"function":"establishConnection","class":"Illuminate\\Redis\\Connectors\\PhpRedisConnector","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/helpers.php","line":263,"function":"Illuminate\\Redis\\Connectors\\{closure}","class":"Illuminate\\Redis\\Connectors\\PhpRedisConnector","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Redis\/Connectors\/PhpRedisConnector.php","line":121,"function":"tap"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Redis\/Connectors\/PhpRedisConnector.php","line":28,"function":"createClient","class":"Illuminate\\Redis\\Connectors\\PhpRedisConnector","type":"->"},{"function":"Illuminate\\Redis\\Connectors\\{closure}","class":"Illuminate\\Redis\\Connectors\\PhpRedisConnector","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Redis\/Connections\/PhpRedisConnection.php","line":536,"function":"call_user_func"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Redis\/Connections\/Connection.php","line":220,"function":"command","class":"Illuminate\\Redis\\Connections\\PhpRedisConnection","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Redis\/Connections\/PhpRedisConnection.php","line":575,"function":"__call","class":"Illuminate\\Redis\\Connections\\Connection","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/horizon\/src\/Repositories\/RedisSupervisorRepository.php","line":152,"function":"__call","class":"Illuminate\\Redis\\Connections\\PhpRedisConnection","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/horizon\/src\/Supervisor.php","line":216,"function":"forget","class":"Laravel\\Horizon\\Repositories\\RedisSupervisorRepository","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/horizon\/src\/Supervisor.php","line":320,"function":"terminate","class":"Laravel\\Horizon\\Supervisor","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/horizon\/src\/Supervisor.php","line":286,"function":"ensureParentIsRunning","class":"Laravel\\Horizon\\Supervisor","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/horizon\/src\/Supervisor.php","line":260,"function":"loop","class":"Laravel\\Horizon\\Supervisor","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/horizon\/src\/Console\/SupervisorCommand.php","line":101,"function":"monitor","class":"Laravel\\Horizon\\Supervisor","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/horizon\/src\/Console\/SupervisorCommand.php","line":76,"function":"start","class":"Laravel\\Horizon\\Console\\SupervisorCommand","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php","line":36,"function":"handle","class":"Laravel\\Horizon\\Console\\SupervisorCommand","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/Util.php","line":40,"function":"Illuminate\\Container\\{closure}","class":"Illuminate\\Container\\BoundMethod","type":"::"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php","line":93,"function":"unwrapIfClosure","class":"Illuminate\\Container\\Util","type":"::"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php","line":37,"function":"callBoundMethod","class":"Illuminate\\Container\\BoundMethod","type":"::"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/Container.php","line":653,"function":"call","class":"Illuminate\\Container\\BoundMethod","type":"::"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Command.php","line":136,"function":"call","class":"Illuminate\\Container\\Container","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/symfony\/console\/Command\/Command.php","line":298,"function":"execute","class":"Illuminate\\Console\\Command","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Command.php","line":121,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/symfony\/console\/Application.php","line":1040,"function":"run","class":"Illuminate\\Console\\Command","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/symfony\/console\/Application.php","line":301,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/symfony\/console\/Application.php","line":171,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Application.php","line":94,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Console\/Kernel.php","line":129,"function":"run","class":"Illuminate\\Console\\Application","type":"->"},{"file":"\/www\/wwwroot\/wyxyyds\/artisan","line":37,"function":"handle","class":"Illuminate\\Foundation\\Console\\Kernel","type":"->"}],"\u0000Exception\u0000previous":null}}, 1731623531, 1731623531))/www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Database/Connection.php#0 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#1 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Database/Connection.php(502): Illuminate\Database\Connection->run()
#2 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Database/Connection.php(454): Illuminate\Database\Connection->statement()
#3 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2980): Illuminate\Database\Connection->insert()
#4 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1657): Illuminate\Database\Query\Builder->insert()
#5 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->__call()
#6 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2132): Illuminate\Database\Eloquent\Model->forwardCallTo()
#7 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2144): Illuminate\Database\Eloquent\Model->__call()
#8 /www/wwwroot/wyxyyds/app/Logging/MysqlLoggerHandler.php(38): Illuminate\Database\Eloquent\Model::__callStatic()
#9 /www/wwwroot/wyxyyds/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): App\Logging\MysqlLoggerHandler->write()
#10 /www/wwwroot/wyxyyds/vendor/monolog/monolog/src/Monolog/Logger.php(400): Monolog\Handler\AbstractProcessingHandler->handle()
#11 /www/wwwroot/wyxyyds/vendor/monolog/monolog/src/Monolog/Logger.php(651): Monolog\Logger->addRecord()
#12 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->error()
#13 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Log/Logger.php(94): Illuminate\Log\Logger->writeLog()
#14 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\Log\Logger->error()
#15 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(252): Illuminate\Log\LogManager->error()
#16 /www/wwwroot/wyxyyds/app/Exceptions/Handler.php(42): Illuminate\Foundation\Exceptions\Handler->report()
#17 /www/wwwroot/wyxyyds/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(57): App\Exceptions\Handler->report()
#18 /www/wwwroot/wyxyyds/vendor/laravel/horizon/src/Supervisor.php(308): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->report()
#19 /www/wwwroot/wyxyyds/vendor/laravel/horizon/src/Supervisor.php(260): Laravel\Horizon\Supervisor->loop()
#20 /www/wwwroot/wyxyyds/vendor/laravel/horizon/src/Console/SupervisorCommand.php(101): Laravel\Horizon\Supervisor->monitor()
#21 /www/wwwroot/wyxyyds/vendor/laravel/horizon/src/Console/SupervisorCommand.php(76): Laravel\Horizon\Console\SupervisorCommand->start()
#22 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\SupervisorCommand->handle()
#23 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#24 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#25 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#26 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#27 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#28 /www/wwwroot/wyxyyds/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#29 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#30 /www/wwwroot/wyxyyds/vendor/symfony/console/Application.php(1040): Illuminate\Console\Command->run()
#31 /www/wwwroot/wyxyyds/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#32 /www/wwwroot/wyxyyds/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#33 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\Component\Console\Application->run()
#34 /www/wwwroot/wyxyyds/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#35 /www/wwwroot/wyxyyds/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#36 {main}  
`

v2_log 内容如下

`<?php $__env->startSection('title', __('Server Error')); ?>
<?php $__env->startSection('code', '500'); ?>
<?php $__env->startSection('message',  __($exception->getMessage() ?: 'Server Error')); ?>

<?php echo $__env->make('errors::minimal', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /www/wwwroot/wyxyyds/resources/views/errors/500.blade.php ENDPATH**/ ?>`

**Comment by forjustice** [comment]
chown -R www:www *

**Comment by likejia1** [comment]
@forjustice 文档里面的常见问题不是写了吗，经典不看文档😅
