### ISSUE TITLE
固定流量的套餐礼品卡也需要添加时长

### ISSUE THREAD

**Issue by w243420707** [wyx2685/v2board#179]
![image](https://github.com/user-attachments/assets/138021bb-af19-498f-8e43-6bd61effde04)

辛苦了佬
固定流量没有时长的套餐如果不填入时间将无法生成

**Comment by wyx2685** [comment]
确实是个问题

**Comment by wyx2685** [comment]
一次性套餐请输入0，不然会有其他问题

**Comment by w243420707** [comment]
> 一次性套餐请输入0，不然会有其他问题

谢谢佬的回复

输入0的话 就等于没有时长了对吧

**Comment by wyx2685** [comment]
更新之后应该就可以，原来的不能

**Comment by w243420707** [comment]
> 更新之后应该就可以，原来的不能

咱们是有最新的发布吗，目前使用的是昨晚更新的

**Comment by w243420707** [comment]
> 更新之后应该就可以，原来的不能

谢谢佬，刚刚看到了 三分钟前有更新
