### ISSUE TITLE
Clash Meta内核软件无法下发HTTPUpgrade传输

### ISSUE THREAD

**Issue by ckaak** [wyx2685/v2board#182]
我尝试修改ClashVerge.php文件，但是只能正确添加     v2ray-http-upgrade: 和v2ray-http-upgrade-fast-open: 参数，但是headers每次都漏掉了。

proxies:
- name: "ws-opts-example"
  type: xxxxx
  network: ws
  ws-opts:
    path: /path
    headers:
      Host: example.com
    max-early-data:
    early-data-header-name:
    v2ray-http-upgrade: false
    v2ray-http-upgrade-fast-open: false

Clash Meta文档给出的参考，是network依旧是ws，只是额外增加v2ray-http-upgrade: 和v2ray-http-upgrade-fast-open: 参数。我还没试Shadowrocket和singbox直接修改php，能否成功下发。貌似跟Helper.php这个文件有关。

**Comment by wyx2685** [comment]
不研究了
不推荐使用
