### ISSUE TITLE
[BUG] 除了Vless 其他节点类型提示 server is not exist

### ISSUE THREAD

**Issue by o0s** [wyx2685/v2board#19]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
最新版本

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
只能对接 vless ，其他节点类型提示 

"message": "server is not exist"

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Oct 21 07:50:09 localhost XrayR[13668]: panic: Panel Start fialed: request http://XXXXXXX/api/v1/server/UniProxy/config failed: {
Oct 21 07:50:09 localhost XrayR[13668]:     "message": "server is not exist"
Oct 21 07:50:09 localhost XrayR[13668]: }, <nil>

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by wyx2685** [comment]
@o0s 说明具体是什么类型节点 什么后端 上配置文件

**Comment by o0s** [comment]
节点类型 ss 和 trojan
后端就是你的修改版
配置文件只修改了 域名/密钥/节点ID/协议类型
Vmess 和 Vless 正常

**Comment by wyx2685** [comment]
@o0s 需要上实际的配置图，只写这些没法定位问题
ss已经测试过没有问题的

**Comment by o0s** [comment]
我giao。我重启了面板服务器，他好了。。。
