### ISSUE TITLE
【报错】用修改版xrayr对接此v2board报错

### ISSUE THREAD

**Issue by zhoushao2018** [wyx2685/v2board#193]
由于修改版xrayr不能来这里提问所以来这里
V2BOARD和修改版xrayr都是些最新版本，
用回原版的xrayr或者修改版V2bX就没问题不报错
咋回事呀好像上个月就开始这样子，网上查找了也没有答案
打扰一下大佬
Dec 24 16:31:53 yunti-lilfe XrayR[20318]: 2024/12/24 16:31:53 [Error] [2704755415] pp/mydispatcher: User V2ray_0.0.0.0_4567|d1ae6366-5d8b-4efe-a652-3c016292dcb8@v2board.user|10062 access tcp:www.gstatic.com:80 reject by rule
Dec 24 16:31:53 yunti-lilfe XrayR[20318]: 2024/12/24 16:31:53 [Error] [285735016] pp/mydispatcher: User V2ray_0.0.0.0_4567|d1ae6366-5d8b-4efe-a652-3c016292dcb8@v2board.user|10062 access tcp:www.gstatic.com:80 reject by rule
Dec 24 16:31:54 yunti-lilfe XrayR[20318]: 2024/12/24 16:31:54 [Error] [3012985944] pp/mydispatcher: User Shadowsocks_0.0.0.0_4560|d1ae6366-5d8b-4efe-a652-3c016292dcb8@v2board.user|10062 access tcp:www.gstatic.com:80 reject by rule
Dec 24 16:31:55 yunti-lilfe XrayR[20318]: 2024/12/24 16:31:55 [Error] [1026550993] pp/mydispatcher: User Shadowsocks_0.0.0.0_4560|d1ae6366-5d8b-4efe-a652-3c016292dcb8@v2board.user|10062 access tcp:1.1.1.1:80 reject by rule
Dec 24 16:31:55 yunti-lilfe XrayR[20318]: 2024/12/24 16:31:55 [Error] [3952592671] pp/mydispatcher: User Shadowsocks_0.0.0.0_4560|d1ae6366-5d8b-4efe-a652-3c016292dcb8@v2board.user|10062 access tcp:www.gstatic.com:80 reject by rule
Dec 24 16:31:56 yunti-lilfe XrayR[20318]: 2024/12/24 16:31:56 [Error] [2147872105] pp/mydispatcher: User V2ray_0.0.0.0_4567|d1ae6366-5d8b-4efe-a652-3c016292dcb8@v2board.user|10062 access tcp:1.1.1.1:80 reject by rule
Dec 24 16:31:57 yunti-lilfe XrayR[20318]: 2024/12/24 16:31:57 [Error] [2956514355] pp/mydispatcher: User Shadowsocks_0.0.0.0_4560|d1ae6366-5d8b-4efe-a652-3c016292dcb8@v2board.user|10062 access tcp:1.1.1.1:80 reject by rule
Dec 24 16:31:58 yunti-lilfe XrayR[20318]: 2024/12/24 16:31:58 [Error] [1863522439] pp/mydispatcher: User Shadowsocks_0.0.0.0_4560|f799f127-0a66-4fdb-ba4c-017f0409b830@v2board.user|13123 access tcp:www.gstatic.com:443 reject by rule

![image](https://github.com/user-attachments/assets/7c282b6f-6a9d-4ee7-b868-b6934dc3c35a)

**Comment by wyx2685** [comment]
不写了嘛 rejected by rule
你们喜欢用面板审计又不会配置
无法解答

**Comment by zhoushao2018** [comment]
> 不写了嘛 rejected by rule 你们喜欢用面板审计又不会配置 无法解答

我勒个去 已解决 搞定了
