### ISSUE TITLE
【功能性问题咨询】节点在线状态的检测机制

### ISSUE THREAD

**Issue by w243420707** [wyx2685/v2board#194]
xiao佬好！

<img width="130" alt="image" src="https://github.com/user-attachments/assets/fa3636e1-9739-477e-9272-071a4c24c068" />

和您问问节点状态页面的这个红蓝的检测是什么机制呀，因为修改了轮询时间之后便全面红点啦，但是实际线路是在线的。

<img width="789" alt="image" src="https://github.com/user-attachments/assets/9c202f3e-9d5a-49eb-8bea-69847ea30c34" />

和您问问这个在可以在哪里修改这个的检测时间吗？

✅ 后端使用的是您修改版的V2bX，singbox内核的config中的timeout部分现在修改的是300

**Comment by wyx2685** [comment]
节点有拉取，黄灯
节点有用户流量上报，蓝灯

**Comment by wyx2685** [comment]
umi.js里面
有兴趣可以自己找
太乱了不想翻

**Comment by w243420707** [comment]
> 看了下应该在这里，默认300秒 https://github.com/wyx2685/v2board/blob/master/app/Services/ServerService.php#L271-L277

感谢xiao佬

**Comment by w243420707** [comment]
> 看了下应该在这里，默认300秒 https://github.com/wyx2685/v2board/blob/master/app/Services/ServerService.php#L271-L277

已测试，就是这个，谢谢xiao佬指点
