### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fsyllkn** [wyx2685/v2board#20]
当前使用的V2Board版本号
V2bx-V2Board v1.7.4
使用的xrayr版本是

Briefly describe the problem you are experiencing
简单描述你遇到的问题
设置了在节点中显示流量剩余功能，关闭该功能的时候，报错。

Screenshot of the reported error(Please do desensitization)
![image](https://github.com/wyx2685/v2board/assets/76274519/23409b40-aaff-4a55-8694-b9a1e07d93d5)

![image](https://github.com/wyx2685/v2board/assets/76274519/eb04ff8c-e288-4112-a5e3-12a49b5dca67)

幸亏提前有备份，恢复后，正常了，不能关闭订阅显示流量功能，关闭报错，无法进入。

**Comment by wyx2685** [comment]
报错看着更像是没有安装完全，和这个设置没关系，能否简述一下部署过程

**Comment by fsyllkn** [comment]
面板站点是在甲骨文的机器上用aapanel安装的，与原来的v2board安装过程一样，我已经多次复现这个问题，只要关闭订阅展示订阅信息这个按钮，就报错，报错后无法访问站点。回到aapanel，恢复一下备份，站点恢复正常。

**Comment by wyx2685** [comment]
代你谷歌了一下，需要关闭防跨站
![1610676485904787.png](https://github.com/wyx2685/v2board/assets/24352157/b69eba85-7466-498e-a6ea-fb35e9fdabd4)

**Comment by fsyllkn** [comment]
感谢大佬，确实是这里的锅，关闭宝塔的设置后，关闭面板的开关报错后，重启了几次vps，目前宝塔和站点面板都恢复正常了
