### ISSUE TITLE
[Feature request] 不知道开发者是否有计划添加singbox订阅，貌似singbox订阅四端+tv都有客户端了。

### ISSUE THREAD

**Issue by heaid** [wyx2685/v2board#22]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。
不知道开发者是否有计划添加singbox订阅，貌似singbox订阅四端+tv都有客户端了。

**Comment by wyx2685** [comment]
已经悄悄加入了singbox.php，可以用flag=sing-box体验

**Comment by heaid** [comment]
感谢开发者的奉献。不知道后续是否支持一键导入的功能

**Comment by wyx2685** [comment]
会逐步完善，有人已经做了
