### ISSUE TITLE
[BUG]条数/页 不固定

### ISSUE THREAD

**Issue by wangkingsten** [wyx2685/v2board#23]
当前使用的V2Board版本号
[a961bff](https://github.com/wyx2685/v2board/commit/a961bfff5396764b33a4b6b1c3ccf727679b99c7)

目前设置50条/页，点击到别的页面之后再回来，或者刷新整个网页几次之后会变回默认的10条/页

**Comment by wangkingsten** [comment]
复现步骤：
当 用户数>10 和 节点数>10
将 用户管理  和 节点管理 都调整成50条/页
首先调整的那一项会变回默认的10条/页

**Comment by wyx2685** [comment]
@wangkingsten 属于原版BUG，能否解决待研究

**Comment by wyx2685** [comment]
已确认是原版即存在问题，修改过于复杂，无法解决
