### ISSUE TITLE
[Feature request] The most powerful v2board panel ❤️

### ISSUE THREAD

**Issue by MrVb0** [wyx2685/v2board#24]
Hello, I just got acquainted with your script and I am very satisfied with it and I hope you are always improving. Thank you .
I have some questions and suggestions regarding your V2Board and XrayR script.

- The first thing that I mentioned earlier in the wrong place: completing and developing the singbox subscription and adding ws and other things along with alpn and...
(If it is possible to categorize node groups for Singbox subscription, it is also very good)

- The next item as a suggestion: With the arrival of applications with support for several protocols (such as Singbox), I suggest that if possible, add support for protocols such as ssh, tuic, etc. to the panel. In some areas, ssh works well, even better than Reality.

- The third item is a question and suggestion: What backend should we use for Hysteria 2? If possible, I suggest you develop the xrayr backend script to use a combination of multiple cores and protocols (hysteria. tuic. ssh. xray. v2fly, ....) ... of course, I think the singbox core supports all of them. .

- The fourth item is another question: How does the user's IP connection restriction option work in the v2board panel? Is it global like sspanel and works on all nodes? (that is, for example, when =1 is set, only 1 IP can be connected *to all nodes at the same time*)

- If possible, I suggest to add the ability to select different options such as alpn, fingerprint, http header, spiderX, etc.

We are very grateful for your time and effort in developing this script.

**Comment by wyx2685** [comment]
1.coming soon
2.tuic v5 in considering, no plan for ssh
3.https://github.com/cedar2025/hysteria can use this backend for hysteria2 now
4.It is global. 1 IP on N nodes will count as N device. Only connection has >100kb in 60s will count as 1 device.Unactive device disappear for 120s.
5.fp, spiderX,http header in todo list.

**Comment by MrVb0** [comment]
In order for the "speed limit" and "device limit" features of the v2board panel to work properly, should the options "speed limit", "device limit" and "global device limit (redis)" be disabled in XrayR config?

Before this, I used XrayR global device limit based on redis and it worked correctly, but unfortunately, this feature was only on the backend side and it was not possible to apply different limits on different plans.
In your v2board panel, this work has become much more beautiful, simpler and more organized.

**Comment by wyx2685** [comment]
@MrVb0 yes
XrayR local setting will override v2board function

**Comment by MrVb0** [comment]
I applied device limit and speed limit options to my plans and created two new accounts for testing
I created an account with the Telegram bot that my friends wrote for me (case 1)
I also created an account through the v2board user management section (case 2).
In case 1, none of the device limit and speed limit factors have been applied to the desired account database.
In case 2, device limit is applied but speed limit is not applied.
Where do you think the problem comes from?

**Comment by wyx2685** [comment]
@MrVb0 1.device_limit added when user buy a plan
2.Im not sure how speed_limit work, I didnt change code about it

**Comment by MrVb0** [comment]
> @MrVb0 2.Im not sure how speed_limit work, I didnt change code about it
I would be grateful if you could check and solve the bug of speedlimit not being applied in v2board.

**Comment by wyx2685** [comment]
I've check the code found not bug this time
User should buy a plan then device_limt/speed_limt will be applied

**Comment by MrVb0** [comment]
> I've check the code found not bug this time User should buy a plan then device_limt/speed_limt will be applied

But unfortunately, as you can see in the picture, even after buying a plan from the site, speed_limit is not applied in the database.

**Comment by wyx2685** [comment]
@MrVb0 please retry step by step and check v2_log database
didn't find any code problem now

**Comment by MrVb0** [comment]
To use the global device limit function of your v2board, it is not necessary that the global device limit xrayr is active?
```
       GlobalDeviceLimitConfig:
         Enable: false # Enable the global device limit of a user
```

**Comment by wyx2685** [comment]
@MrVb0 yes

**Comment by wyx2685** [comment]
> Please explain more about DeviceOnlineMinTraffic option. For example, in a program like Singbox that receives pings from all servers every minute, what value should we set this option to in order not to cause problems?

every 60s xrayr node will send traffic and online_device to panel.
If 1 user_ip use more traffic than this value in 60s,it will count as 1 device.
personally i think 100-1000kb is recommended

**Comment by MrVb0** [comment]
That is, when a user is downloading a file or watching a video with a download speed of 1 MB/s, the system is supposed to detect it on more than 1 device?!
How can I disable this feature for testing?
If I disable this feature, will the number of IPs in all nodes be checked and controlled globally?

**Comment by wyx2685** [comment]
@MrVb0 no matter speed. it will only count as 1 device when traffic reach the value.
device numbers base on ip_nodeid, same ip on multi node will count as more than one device

**Comment by ZHQSM** [comment]
大佬，上报的阈值在哪里改 测试如果个人切换节点太快 很容易超过设备数 目前好像是100kb吧

**Comment by lanziii** [comment]
@ZHQSM 配置文件里。默认安装不覆盖。你先卸载再安装就会出现第32行

**Comment by wyx2685** [comment]
@ZHQSM 在配置模板里
