### ISSUE TITLE
关于hy2节点对接问题

### ISSUE THREAD

**Issue by zheng-yong** [wyx2685/v2board#25]
谢谢老哥的分享，我有2点问题：
1、请问与hy2对接，hy2服务端要配置对接参数吗
2、请问hy2的订阅链接，哪些客户端软件支持，谢谢！

**Comment by zheng-yong** [comment]
hy2使用的是：https://github.com/cedar2025/hysteria

**Comment by wyx2685** [comment]
看那边readme吧

**Comment by rainbowshine521** [comment]
好像订阅无法更新到HY2节点

**Comment by wyx2685** [comment]
> 好像订阅无法更新到HY2节点

别光好像，拿东西出来，没头没尾。。。
