### ISSUE TITLE
尊敬的开发者你好，原版迁移似乎遇到一点问题

### ISSUE THREAD

**Issue by 1403972480** [wyx2685/v2board#27]
您好我从原版1.7.3迁移到您项目的v1.7.4版本后，我执行了一遍./update.sh 销售统计图加载不出和用户设备统计不显示数量有设备在线一直显示为0等情况，还请您在百忙之中抽空看一看，非常感谢！！
![image_2023-11-04_12-19-06](https://github.com/wyx2685/v2board/assets/53146793/6b817661-e854-4d66-b65d-970b5a0b4225)
![image](https://github.com/wyx2685/v2board/assets/53146793/9a41db39-a5f5-42c1-973b-c76bd49faf32)
![image](https://github.com/wyx2685/v2board/assets/53146793/f5ec6c74-0b23-4a22-81ea-a919f7be1541)

**Comment by wyx2685** [comment]
在网站目录执行以下命令以清除并重建设置缓存
php artisan config:clear
php artisan config:cache

设备数统计需要配合魔改的xrayr后端使用

**Comment by 1403972480** [comment]
感谢您的回答，我执行完三行命令之后销售统计图依旧不显示，虽然没有影响，有点小瑕疵，谢谢您

**Comment by wyx2685** [comment]
@1403972480 需要等待一天进行流量统计，显示的是昨日流量

**Comment by 1403972480** [comment]
您好，流量统计图正常显示，销售统计图显示销售金额，数量空白不显示

**Comment by wyx2685** [comment]
@1403972480 麻烦检查一下数据库v2_log表是否有报错信息

**Comment by 1403972480** [comment]
开发者您好，检查了一下v2_log，只有我自己修改设置的日志，并没有报错信息。
刚刚发现一个倍率问题，节点倍率是1，可是使用288MB流量后，用户面板扣除了将近3倍的流量
这是使用流量前
![image](https://github.com/wyx2685/v2board/assets/53146793/e47ec8ec-9afa-46dc-afa8-f456320b636b)
这是使用流量后
![image](https://github.com/wyx2685/v2board/assets/53146793/fe1304a3-e88c-4bec-8a05-be753de8c226)
这是流量使用量
![image](https://github.com/wyx2685/v2board/assets/53146793/9d4c002d-a4c8-4b69-9146-d67a94d3d214)
还请您帮忙看一看，非常感谢

**Comment by 1403972480** [comment]
开发者您好，检查了一下v2_log，只有我自己修改设置的日志，并没有报错信息。
刚刚发现一个倍率问题，父子节点倍率都是1，可是使用560MB流量后，用户面板扣除了将近3倍的流量
这是使用流量前
![image](https://github.com/wyx2685/v2board/assets/53146793/75bb565f-ac56-4205-b77c-144c1333630d)
这是使用流量后
![image](https://github.com/wyx2685/v2board/assets/53146793/55ab249a-fbff-4120-b8a9-1bec3674049c)
这是流量使用量
![image](https://github.com/wyx2685/v2board/assets/53146793/ca84065e-3e92-4f7d-9ffc-244b3e99c588)
测试了很多遍，差不多是3倍，还请您帮忙看一看，非常感谢

**Comment by wyx2685** [comment]
1.v2_log有没有 统计任务执行完毕 的记录
2.v2_stat表有没有内容

3倍流量这个真没思路，详细说说升级迁移过程和节点配置？

**Comment by 1403972480** [comment]
v2_stat表没有内容，测试支付过，问题依旧
![image](https://github.com/wyx2685/v2board/assets/53146793/5ba5993b-322c-4501-a50b-6ace3cb7ab76)

最先开始使用的原版1.7.3版本，随后我拉取您的1.7.4目录搭建了一个全新的v2b，随后设置好v2b后台面板的系统设置内容，从原版1.7.3的数据库直接导入，随后发现报错，显示不了用户资料，后台提示有未知问题请联系管理员，后台看到 lssues 有原版迁移的例子，最后执行了一遍./update.sh命令就可以使用了，然后就出现了统计图无法显示，测试支付了一下，也无法显示，还有3倍计流的问题，还请您帮忙看看

**Comment by wyx2685** [comment]
@1403972480 v2_stat也是0点统计，等一天看看吧

3倍流量说说节点配置情况

**Comment by 1403972480** [comment]
父节点用的ss直连落地机，随后用子节点中转父节点，所有的倍率都是1
![image](https://github.com/wyx2685/v2board/assets/53146793/0a7d9677-09a4-41c1-8bfb-da9512bdb6aa)

**Comment by wyx2685** [comment]
@1403972480 用的后端是XrayR吗

**Comment by 1403972480** [comment]
是的，不是修改版，是原版
![image](https://github.com/wyx2685/v2board/assets/53146793/fd4e9681-ba11-43de-a143-7f70be362ac2)

**Comment by 1403972480** [comment]
尊敬的开发者您好，刚刚我使用您的xrayr魔改版分支，测试流量消耗是正常的，非常抱歉打扰您

**Comment by wyx2685** [comment]
@1403972480 更奇怪了，想不明白...

**Comment by 1403972480** [comment]
现在是单独直连ss，没有父子节点，倍率10倍详情如下
![image](https://github.com/wyx2685/v2board/assets/53146793/20d820d7-502b-4b0c-8ed6-9116cfd42d44)
使用前
![image](https://github.com/wyx2685/v2board/assets/53146793/21ac5998-5e95-42e8-abdd-17c124296d02)
使用后
![image](https://github.com/wyx2685/v2board/assets/53146793/14b47da1-9de9-4051-be91-a75054614ef2)

**Comment by 1403972480** [comment]
您好，我用回了1.7.4原版，计流问题依然存在，我认为是进程守护开了双倍进程，您这个地方有修改么，我事先在同一台机器，宝塔上运行了两个版本的v2b面板，现在重装之后双倍计流问题依旧存在，只貌似存在于父子节点，如果单独使用直连节点倍率貌似是正常的

**Comment by kevlau1** [comment]
> 您好，我用回了1.7.4原版，计流问题依然存在，我认为是进程守护开了双倍进程，您这个地方有修改么，我事先在同一台机器，宝塔上运行了两个版本的v2b面板，现在重装之后双倍计流问题依旧存在，只貌似存在于父子节点，如果单独使用直连节点倍率貌似是正常的

同时运行2个v2b需要redis再创建一个实例，缓存分开就可以解决了

**Comment by 1403972480** [comment]
我现在只保留一个，目前流量统计依然还是双倍计流，该怎么办呢

**Comment by kevlau1** [comment]
大佬前面不是说了吗，清除并重建设置缓存,重启horizon

**Comment by manet9** [comment]
在线设备也有问题，如果用sing-box就统计不到设备数，貌似只有v2ray内核才能统计到

**Comment by wyx2685** [comment]
> 在线设备也有问题，总之很乱

可以发详细问题这边再看看

**Comment by manet9** [comment]
设置在线设备3/3，登录2台就会显示3/3，就算登录1台设备偶尔也会显示3/3

**Comment by wyx2685** [comment]
> 设置在线设备3/3，登录2台就会显示3/3，就算登录1台设备偶尔也会显示3/3

1.统计以IP为准，需要节点获得用户端真实IP才能准确统计
2.防测速误统计需要设置合适的流量上报阈值

**Comment by manet9** [comment]
还有个问题，原xrayr后端默认支持ipv6出口，你的脚本不支持

**Comment by wyx2685** [comment]
有需求先自己改一下custom_outbound吧
后面我改成prefer ipv4

**Comment by manet9** [comment]
还有个小问题，用surfboard无法获取到远程dns，更换原xrayr后可以远程获取，这个需要更改哪里？

**Comment by lanziii** [comment]
@manet9 技术问题50u起步

**Comment by waiwaiwq** [comment]
@lanziii 我10U就可以
