### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GH6324** [wyx2685/v2board#3]
安卓Nekobox客户端默认订阅会订阅失败。。订阅时候的用户代理必须指定才能正常下发订阅。。
![image](https://github.com/wyx2685/v2board/assets/47879885/0857ef0f-6b70-47f4-a24c-539ea42106ce)
订阅失败就会如下图所示
![f97368bb52aa67832f060b2c871e52b](https://github.com/wyx2685/v2board/assets/47879885/fec6b694-0732-4db9-8bd4-6b3c51db88f7)

**Comment by wyx2685** [comment]
无法复现，我1.2.2版本获取订阅正常，请提供详细说明
