### ISSUE TITLE
订阅链接的问题请教

### ISSUE THREAD

**Issue by 759071793** [wyx2685/v2board#30]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.4

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
请问大佬，为啥我复制的订阅链接导入到passwall2默认使用的是sing-box内核，但是节点无法使用，或者延迟超级高。
修改哪里可以让订阅链接导入默认是xray内核呢？

直接点击按钮导入到手机客户端就没有问题。

--------

**Comment by wyx2685** [comment]
不是很清楚这个内核判断逻辑，可能需要去问passwall2那边
我粗略看了一下passwall2获取订阅的行为就是浏览器获取，这个是只能得到节点信息的
