### ISSUE TITLE
开发者你好  建好前端之后的可以正常进入但是登录不上

### ISSUE THREAD

**Issue by Cookrs** [wyx2685/v2board#31]
![A20A3D34-D8D7-471B-80F6-DE3736162EC0](https://github.com/wyx2685/v2board/assets/94035608/342f9ab7-ace5-4ca8-91b4-0d0cf9491106)

**Comment by Cookrs** [comment]
请问我该如何操作还能正常使用

**Comment by wyx2685** [comment]
请详细描述过程及问题

**Comment by Cookrs** [comment]
> 请详细描述过程及问题

就是搭建好前端之后  我打开管理后台登录页面输入账号密码 登录的时候提示上边截图这个

**Comment by wyx2685** [comment]
@Cookrs 搭建步骤呢，请核实按正确步骤搭建好前端

**Comment by Cookrs** [comment]
> @Cookrs步骤搭建呢，请重新安装正确按步骤搭建好前端

我是根据https://lala.im/8854.html这个教程搭建

**Comment by lanziii** [comment]
@Cookrs 这边50u提供代搭建服务呢！

**Comment by wyx2685** [comment]
登录出错通常是REDIS没有配置好，或者MYSQL数据库有问题，请排查

**Comment by isisno** [comment]
按照原版v2board的方法安装就够啦，出现这个错误提示经常是没有打开权限

**Comment by ipv6next** [comment]
同样的问题，安装没有报错。

**Comment by wyx2685** [comment]
@ipv6next 请自查redis和文件目录权限
