### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by hexsen929** [wyx2685/v2board#34]
大佬你好，由于您的分支[V2bX](https://github.com/wyx2685/V2bX)，没有开启issue，所以来这里咨询下。

我是纯ipv6的机器，使用V2bX创建的hy2节点，没有开启监听udp6端口，只开启监听了udp的端口。导致节点无法使用。
![image](https://github.com/wyx2685/v2board/assets/23308600/8c6ce684-5ded-499a-857e-317d8df7ba81)

**Comment by wyx2685** [comment]
@hexsen929 你先试试写::

**Comment by hexsen929** [comment]
> ::

哇，大佬还没睡，config改::已成功监听，有没有办法可以同时监听呢，期待下一个版本

**Comment by hexsen929** [comment]
非常感谢！

**Comment by hexsen929** [comment]
您的Xrayr就没有这个问题

**Comment by wyx2685** [comment]
@hexsen929 这个是sing-box和xray内核的问题，xray监听0.0.0.0会自动改成:::

**Comment by hexsen929** [comment]
> @hexsen929 这个是sing-box和xray内核的问题，xray监听0.0.0.0会自动改成:::

是的，[V2bX](https://github.com/wyx2685/V2bX)用xray内核无法使用hy2，只能用sing-box，这个问题我只能去sing-box提了。谢谢你

**Comment by wyx2685** [comment]
我后面优化一下脚本
