### ISSUE TITLE
V2bx问题

### ISSUE THREAD

**Issue by hexsen929** [wyx2685/v2board#36]
大佬，V2bx搭建的节点访问path，会显示handshake error: bad "Upgrade" header，这样套cf的cdn，只能套标准的80和443端口。
不知道问题出在哪里。。
xrayr搭建的vmess就是正常的Bad Request。

**Comment by wyx2685** [comment]
@hexsen929 估计代码实现不一样，后面看看

**Comment by hexsen929** [comment]
> @hexsen929 估计代码实现不一样，后面看看

不好意思，可以套cf，我cf后台忘记重写了
