### ISSUE TITLE
[BUG] php8.2 跟新adapterman报错

### ISSUE THREAD

**Issue by ZHQSM** [wyx2685/v2board#38]
Reading ./composer.json (/www/wwwroot/xxx/composer.json)
Loading config file ./composer.json (/www/wwwroot/xxx/composer.json)
Checked CA file /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem: valid
Executing command (/www/wwwroot/xxxxxx): 'git' 'branch' '-a' '--no-color' '--no-abbrev' '-v'
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json

Reading /www/wwwroot/xxxxx/vendor/composer/installed.json
Loading composer repositories with package information
Reading /root/.cache/composer/repo/https---repo.packagist.org/packages.json from cache
Downloading https://repo.packagist.org/packages.json if modified
[200] https://repo.packagist.org/packages.json

./update.sh: 行 17: 20024 段错误               php composer.phar update -vvv
./update.sh: 行 22: 20034 段错误               php composer.phar require joanhey/adapterman

**Comment by wyx2685** [comment]
@ZHQSM 这个日志看不到具体问题
