### ISSUE TITLE
v2bx hy2协议无法对接v2board

### ISSUE THREAD

**Issue by johnsy616** [wyx2685/v2board#39]
你好，我用你的修改版v2board和v2bx, 配置hy2节点后错误提示

error: add new node error: build inbound error: unsupported node type: hysteria, Only support: V2ray, Trojan, Shadowsocks"
Dec 02 14:19:44 racknerd-ec2d50 systemd[1]: V2bX.service: Succeeded.
Dec 02 14:31:04 racknerd-ec2d50 systemd[1]: Started V2bX Service.

**Comment by wyx2685** [comment]
选错内核

**Comment by johnsy616** [comment]
真的是，选sing之后就对接上了，感谢
