### ISSUE TITLE
[BUG]shadowsocks订阅无路径

### ISSUE THREAD

**Issue by AllCheeks** [wyx2685/v2board#4]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.4

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
使用v2rayN
shadowsocks订阅不下发路径和传输协议

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
https://s1.ax1x.com/2023/09/02/pPBYQYj.jpg
Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by wyx2685** [comment]
订阅套餐 有效时间 用其他协议有没有
这些自查一下，这个分支只改过vless

**Comment by AllCheeks** [comment]
其他协议没有问题，就是ss有问题
