### ISSUE TITLE
[BUG]关于webman的配置

### ISSUE THREAD

**Issue by Sugerland** [wyx2685/v2board#40]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.4

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
升级至最新版本(webman)之后，admin后台报错，显示请求失败
初步推测是缺失某些文件以及某些权限异常，无法判定admin是否登录
我的升级步骤是
卸载原有的php插件 卸载php 安装8.1 安装插件 网站内选择切换至8.1
修改伪静态， 升级面板
用户端无报错 开启webman无报错
伪静态规则
location /downloads {
}

location / {  
    # try_files $uri $uri/ /index.php$is_args$query_string;  
      proxy_pass http://127.0.0.1:6600;
}

location ~ .*\.(js|css)?$
{
    expires      1h;
    error_log off;
    access_log /dev/null; 
}

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![屏幕截图 2023-12-02 151203](https://github.com/wyx2685/v2board/assets/81863360/e3e7a9c2-2b26-41c0-8796-84c381b798da)
![屏幕截图 2023-12-02 151337](https://github.com/wyx2685/v2board/assets/81863360/17206d43-c0e4-428c-89ad-0109e86d1f63)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![屏幕截图 2023-12-02 151512](https://github.com/wyx2685/v2board/assets/81863360/8702f184-fbe5-49dd-a974-6e7efcead6a4)
![屏幕截图 2023-12-02 151433](https://github.com/wyx2685/v2board/assets/81863360/57f90fc0-71ef-4530-ae4b-1694e2428f8e)

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by wyx2685** [comment]
宝塔使用时php没有正确加载redis扩展，通用的解决方法在研究。可以自己在cli-php.ini加入以下

extension=/php模块目录/redis.so

另外你的nginx反代也要改改，不然静态资源用不了

**Comment by wyx2685** [comment]
location /downloads {
}

location / {
try_files $uri $uri/ @backend
}

location @backend {
proxy_pass http://127.0.0.1:6600;
}

location ~ .*.(js|css)?$
{
expires 1h;
error_log off;
access_log /dev/null;
}

**Comment by Sugerland** [comment]
;

**Comment by wyx2685** [comment]
@Sugerland kk

**Comment by Sugerland** [comment]
我直接照抄了
location /downloads {
}

location / {
try_files $uri $uri/ @backend;
}

location @backend {
proxy_pass http://127.0.0.1:6600;
}

location ~ .*.(js|css)?$
{
expires 1h;
error_log off;
access_log /dev/null;
}
也检查了一下
extension=/php模块目录/redis.so
![屏幕截图 2023-12-02 153959](https://github.com/wyx2685/v2board/assets/81863360/fc95614b-7e31-475e-95ea-d42adccd77a2)
依然出现报错

而且发现另外一个bug

用户导入订阅时的地址变成了
http://127.0.0.1:6000/xxxx

**Comment by wyx2685** [comment]
@Sugerland 不是检查了一下，是要写进cli-php.ini

**Comment by Sugerland** [comment]
我发现有两个cli-php.ini文件
一个在网站目录 一个在comporse目录
我都添加了redis.so
后台不访问不报错，但是无法正常保存设置
一保存就显示请求失败

**Comment by Sugerland** [comment]
GET https://xxx/assets/admin/custom.css?v=1.7.5.2685 net::ERR_ABORTED 404 (Not Found)
真的有这个custom.css?v=1.7.5.2685 文件吗

**Comment by wyx2685** [comment]
@Sugerland 你说的话看不懂...

**Comment by ZHQSM** [comment]
@backend; 这个是什么 有点没理解 写一模一样的》？

**Comment by wyx2685** [comment]
>  GET https://xxx/assets/admin/custom.css?v=1.7.5.2685 net::ERR_ABORTED 404 (Not Found)
> 真的有这个custom.css?v=1.7.5.2685 文件吗

这个是给你自定义css用的
没有也不影响

**Comment by wyx2685** [comment]
> @backend; 这个是什么 有点没理解 写一模一样的》？

这个你看不懂就照着写

**Comment by ZHQSM** [comment]
改完了 也重启了webman  前端卡登录 后端404  这个太难整了 5555

**Comment by wyx2685** [comment]
我后面换个宝塔环境再出配套说明吧
现在这样太费劲了

**Comment by ZHQSM** [comment]
谢谢  期待教程 webman 以前没接触过 搞了我两天了 我还是没弄好

**Comment by wyx2685** [comment]
https://github.com/vlesstop/xiaoV2b/blob/main/README.md
