### ISSUE TITLE
HY2节点设置上下行带宽，没有下发到客户端

### ISSUE THREAD

**Issue by johnsy616** [wyx2685/v2board#41]
HY2节点设置了上下行带宽，没有下发到客户端，
我设置了上传下载都是200，下发订阅后nekobox上传下载两个值都是0

**Comment by wyx2685** [comment]
默认不下发

**Comment by johnsy616** [comment]
如何开启下发？客户端没下发带宽配置，服务端配置文件里也没地方配带宽

**Comment by wyx2685** [comment]
客户端下发多少都不合适，需要的自己写
