### ISSUE TITLE
The best aapanel configuration for v2board

### ISSUE THREAD

**Issue by MrVb0** [wyx2685/v2board#42]
Hi, I want to start a new v2board server with your script
Please suggest the best configuration for your v2board (the most ideal and the best)
server OS / nginx version / php version / mysql version / disabled php functions / php extensions / ....

**Comment by MrVb0** [comment]
> ☑️ Nginx any version
> ☑️ MySQL 5.7
> ☑️ PHP 8.1 (if you don’t see 8.1, don’t select it first, go to the App Store to install it) Select Fast to quickly compile and install.
> 
> Install extension
> aaPanel Panel > App Store > Find PHP 8.1, click Setting > Install extentions, select the following extensions to install
> redis
> fileinfo
> swoole4
> readline
> event
> 
> Remove prohibited function
> aaPanel Panel > App Store > Find PHP 8.1 and click Setting > Disabled functions to remove the following functions from the list
> putenv
> proc_open
> pcntl_alarm
> pcntl_signal

is it ok ?

**Comment by wyx2685** [comment]
@MrVb0 if there show aapanel then i dont know
