### ISSUE TITLE
检测 V2bX 版本失败，可能是超出 Github API 限制，请稍后再试，或手动指定 V2bX 版本安装

### ISSUE THREAD

**Issue by johnsy616** [wyx2685/v2board#43]
作者你好，在有些vps上安装v2bx会有这个提示，有的就能正常安装
检测 V2bX 版本失败，可能是超出 Github API 限制，请稍后再试，或手动指定 V2bX 版本安装

**Comment by johnsy616** [comment]
那如何能按照提示说的手动指定安装版本？

**Comment by wyx2685** [comment]
vps连不上github请自行解决
