### ISSUE TITLE
从原版升级显示这个该则么办

### ISSUE THREAD

**Issue by caikun74** [wyx2685/v2board#48]
PDOException 

  SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO)

  at vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70
    66|         if (class_exists(PDOConnection::class) && ! $this->isPersistentConnection($options)) {
    67|             return new PDOConnection($dsn, $username, $password, $options);
    68|         }
    69| 
  > 70|         return new PDO($dsn, $username, $password, $options);
    71|     }
    72| 
    73|     /**
    74|      * Determine if the connection is persistent.

      +6 vendor frames 
  7   app/Console/Commands/V2boardUpdate.php:42
      Illuminate\Database\Connection::getPdo()

      +13 vendor frames 
  21  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
root@racknerd-b08883:~# git ls
git: 'ls' is not a git command. See 'git --help'.

The most similar command is
        log

**Comment by wyx2685** [comment]
@caikun74 sql用户密码不对，自查升级步骤
