### ISSUE TITLE
[BUG]流量统计只统计上行流量 不统计下行流量 

### ISSUE THREAD

**Issue by Franklyingg** [wyx2685/v2board#49]
最新的面板和Xray修改版后端,所有功能均正常（包括上报在线设备数）

用户流量统计只统计上行流量（有时候只上报上行流量，有时候会把下行流量按照上行流量使用量上报）,包括面板的节点流量统计也只统计上行流量

重装过面板和后端都没用,不知道是面板还是后端的问题，请问有没有日志能看xrayr上报的流量记录
![{7AE69934-8007-4099-BC97-6940B8EE8078}](https://github.com/wyx2685/v2board/assets/147582534/97ebd041-b0c2-458f-843e-ee17e665b931)

**Comment by Franklyingg** [comment]
原来用原版面板和后端的时候流量统计是正常的

**Comment by wyx2685** [comment]
@Franklyingg 请再做一下详细的测试，目前没有发现其他人有相同问题

**Comment by Franklyingg** [comment]
@wyx2685  
应该是xrayr的问题,试验了xrayr和v2bx的xrayr 12.12和12.02的版本都不行
但是用v2bx的singbox流量统计就正常,在我的几台机器上都存在这个问题

顺带问一下 singbox之后可以支持在线设备检测吗

**Comment by Franklyingg** [comment]
@wyx2685
应该是xrayr的问题,试验了xrayr和v2bx的xrayr 12.12和12.02的版本都不行
但是用v2bx的singbox流量统计就正常,而且在我的几台机器上都可以复现这个情况

**Comment by wyx2685** [comment]
因为我自用xrayr没发现同样问题，需要给详细信息，不然没法排查

**Comment by Franklyingg** [comment]
好的  打扰您了

我这边xrayr日志和面板log都没有报错记录, 不知道该给出什么详细信息 
如果您这边也没有什么头绪的话 就close issue吧 怪不好意思的
