### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by skyrockgz** [wyx2685/v2board#5]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号 1.7.4
--------

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
1.新增vless节点的时候提示：遇到了些问题，我们正在处理
然后新增节点失败
2.选择Reality时候，只能编辑servicename

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

其他：我本来安装的是原版的v2board 1.7.3  
在wwwroot/site目录下覆盖本项目最新版本后  执行php artisan v2board:update

**Comment by wyx2685** [comment]
请尝试清空缓存

**Comment by skyrockgz** [comment]
php artisan config:clear 执行后未能排除故障

**Comment by wyx2685** [comment]
我是说浏览器缓存清了试一下，有可能用的旧js

**Comment by skyrockgz** [comment]
浏览器缓存也试过了，还是不行，错误依旧。reality不选正常

**Comment by wyx2685** [comment]
能否尝试重新装依赖
composer update
composer install

**Comment by wyx2685** [comment]
原版本composer没有paragonie/sodium_compat这个依赖，装了就好了

**Comment by skyrockgz** [comment]
> 能否尝试重新装依赖 php composer.phar update php composer.phar install

感谢大佬！按照这条重新更新了就可以了
