### ISSUE TITLE
[BUG]更新前端到最新后，重新登录提示500错误

### ISSUE THREAD

**Issue by nagaame** [wyx2685/v2board#55]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号

版本是源代码最新

--------

Briefly describe the problem you are experiencing
简单描述你遇到的问题

普通用户登录服务器提示500错误，管理界面没有错误正常显示

--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）

截图如下

<img width="810" alt="2024-01-03_16-04-46" src="https://github.com/wyx2685/v2board/assets/6214936/ca83ff6a-fcdf-4c56-9843-f494c668a072">

--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）

没有看到当天的日志，日志都是一个月两个月前的

--------

**Comment by wyx2685** [comment]
麻烦再更新看下

**Comment by nagaame** [comment]
可以了，感谢🙏
