### ISSUE TITLE
[BUG]升级最新版本后进入主题配置报错

### ISSUE THREAD

**Issue by sysytemofxxx** [wyx2685/v2board#57]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.4

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
]升级最新版本后进入主题配置报错

请求失败
default初始化失败

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

<img width="383" alt="image" src="https://github.com/wyx2685/v2board/assets/28782855/ebd8ab69-5fee-476d-912e-0e1398ce78ea">

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by wyx2685** [comment]
@sysytemofxxx 暂时查不出来，看看有没有相同反馈的

**Comment by sysytemofxxx** [comment]
伪静态添加webman绕过主题接口后正常
/theme/
