### ISSUE TITLE
[BUG]无法添加服务器

### ISSUE THREAD

**Issue by c6161039** [wyx2685/v2board#59]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
-------- 1.7.5

Briefly describe the problem you are experiencing
简单描述你遇到的问题
-------- 在添加歇斯底里的服务器时失败 提示

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
 
![image](https://github.com/wyx2685/v2board/assets/53891936/ab311b02-c541-4342-8b54-4aaeac05e689)

**Comment by wyx2685** [comment]
@c6161039 v1必须填写带宽信息

**Comment by c6161039** [comment]
v1 v2均无法使用 添加方式为您的 v2box

**Comment by c6161039** [comment]
是否能添加您的 联系方式 详细发给您

**Comment by lanziii** [comment]
@c6161039 https://t.me/unofficialV2board

**Comment by ckaak** [comment]
> @c6161039 v1必须填写带宽信息

#61 我觉得应该是这样问题，是混淆方式obfs参数没写入进去。

**Comment by wyx2685** [comment]
https://github.com/wyx2685/v2board/commit/65c530dd29753a6c456f3a6666aaa5a00508f7d1
