### ISSUE TITLE
[BUG]我知道为什么面板无法添加hy v1了

### ISSUE THREAD

**Issue by ckaak** [wyx2685/v2board#61]
在添加hy v1节点的会出现报错，但是如果你选择v2，再选择v1就行了。

原因就是：添加v1的时候少了一个，混淆方式obfs参数。第一次添加的时候不知道为啥没有显示出来。

还有一个问题就是如果用v2bx的时候，节点类型选择hy1也是无法正常对接的，如果你在v2b面板强制打开混淆方式obfs就可以。

我觉得是这个参数没正确写入。

**Comment by wyx2685** [comment]
https://github.com/wyx2685/v2board/commit/65c530dd29753a6c456f3a6666aaa5a00508f7d1
