### ISSUE TITLE
[Feature request]关于端口跳转的功能

### ISSUE THREAD

**Issue by xielidun** [wyx2685/v2board#63]
非常感谢老大贡献了该面板
但随着时间的推移，hysteria2单端口被封端口成了日常
而面板中无法添加范围端口，请问将来会有添加端口跳跃的可能性吗

**Comment by wyx2685** [comment]
https://github.com/wyx2685/v2board/commit/954e6f8e68bec771fc2bc2dd27175a74557a7093
