### ISSUE TITLE
[BUG] Trojan 设置 允许不安全 为 是 后，v2ray 更新订阅后 跳过证书验证(allowInsecure) 仍然为 false

### ISSUE THREAD

**Issue by imJack6** [wyx2685/v2board#70]
The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.5

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
`Trojan` 设置 `允许不安全` 为 `是` 后，v2ray 更新订阅后 `跳过证书验证(allowInsecure)` 仍然为 `false`，Hysteria2 正常，其它3个没有试

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![image](https://github.com/wyx2685/v2board/assets/58357771/5b502c84-f53c-445e-b44b-d068ac854990)

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
无

**Comment by wyx2685** [comment]
@imJack6 不是bug，trojan客户端很多不接受不安全证书

**Comment by imJack6** [comment]
> @imJack6 不是bug，trojan客户端很多不接受不安全证书

我只有手动在 v2rayN 里面把 跳过证书验证(allowInsecure) 改成 true 才能用，不行我还是去申请证书吧
