### ISSUE TITLE
[提问]邮件发送失败

### ISSUE THREAD

**Issue by SunHead1111** [wyx2685/v2board#74]
v1.7.5

邮件发送失败

数据库中v2_mail_log的错误提示：Cannot send message without a sender address

**Comment by wyx2685** [comment]
@SunHead1111 issue区不接受提问

**Comment by SunHead1111** [comment]
> @SunHead1111 issue区不接受提问

可是并没有找到其它地方能提……或者说我应该改成[BUG]？（很抱歉没怎么用过GitHub……）
而且我看见好像也有其它人在这提问的样子？

**Comment by wyx2685** [comment]
改成BUG他也不是BUG，说明里面有群地址
