### ISSUE TITLE
1.75版本，导出客户邮箱一列，部分客户不显示邮箱，显示订阅链接，订阅链接处则是空[BUG]

### ISSUE THREAD

**Issue by feitutu101** [wyx2685/v2board#76]
1.75版本，导出CSV，部分客户邮箱列会显示订阅链接。
我在“订阅URL”里放了2个订阅链接，不知道是不是这原因。

**Comment by feitutu101** [comment]
![BUG01](https://github.com/wyx2685/v2board/assets/132899050/039d413a-abbd-4add-86da-367b9b4cf18e)

**Comment by feitutu101** [comment]
另外有时候会显示超终端，这个会影响实际限制吗？
![chaozhongduan](https://github.com/wyx2685/v2board/assets/132899050/e4d16ef2-55bb-4348-bba5-b546943937d7)

**Comment by wyx2685** [comment]
@feitutu101 不懂啥问题，有人懂就修
超了就限制

**Comment by feitutu101** [comment]
> @feitutu101不懂啥限制问题，有人懂就修 超了就

好吧

**Comment by feitutu101** [comment]
> @feitutu101不懂啥限制问题，有人懂就修 超了就



> @feitutu101 不懂啥问题，有人懂就修 超了就限制

我测试了一下，是2个URL导致的。放一个就没问题。
