### ISSUE TITLE
[BUG] Singbox一键订阅会出现多余换行符。

### ISSUE THREAD

**Issue by Riverboat8865** [wyx2685/v2board#78]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------

wyx265的版本。

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------

客户端一键订阅有多余的字符"\n"，设备为安卓。出现“Error parse "\nhttps://xxxx/api/v1/client/subscribe?token= xxxxx&flag=sing-box": net/url: invalid control character in URL 无法配置本地端口”。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by wyx2685** [comment]
目前无相同反馈
