### ISSUE TITLE
[BUG]流量统计信息携带倍率后前后端显示不一样

### ISSUE THREAD

**Issue by Furota** [wyx2685/v2board#8]
The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.4 于8/28日 git clone

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
流量统计信息携带倍率后前后端显示不一样，下图为我测试使用210M 0.01倍率节点的流量，ADMIN侧和用户侧所显示的信息

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
ADMIN侧显示
![image](https://github.com/wyx2685/v2board/assets/143926437/85c28b6a-cb1b-4ec3-bf7c-13f0e3dfa1da)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
用户侧显示
![image](https://github.com/wyx2685/v2board/assets/143926437/a4b82315-ff0c-47b9-aa28-d3292b704ebe)
复现方式：新建一个reality节点，设定倍率为0.01，会出现用户侧显示流量信息异常的问题

此外，我不确定显示问题是否会导致实际的流量使用情况计算有误，因此我会开一个新订阅用于测试。
由于V2board 1.7.4的隔天统计特性，我会在明天才能看到测试结果，到时候我会把结果进一步上传。

**Comment by wyx2685** [comment]
目前看，管理后台显示的是乘过倍率的结果，用户侧显示的是实际上下行
就是这个量可能有点不对，继续查找中
