### ISSUE TITLE
[Help]太容易被墙了，请求协助

### ISSUE THREAD

**Issue by NikoCat233** [wyx2685/v2board#84]
本人使用该项目搭建的站点只给了3-5个人用，没有上过搜索聊天，1个礼拜吃墙了
听说更换主题能改善v2board被墙的问题，但是我更换了几个主题都不怎么支持hysteria，没有该项目默认主题适配的好。
请问能给出抵抗秒墙的建议吗，或者说能不能添加一个给用户前端路径分流的功能，谢谢！

**Comment by wyx2685** [comment]
@NikoCat233 墙域名还是墙ip啊

**Comment by NikoCat233** [comment]
域名和ip一起干了

**Comment by lanziii** [comment]
@NikoCat233 你不套 cf 试试

**Comment by NikoCat233** [comment]
不是假墙 是域名被锁+污染了

**Comment by NikoCat233** [comment]
直连的也被干死了

**Comment by NikoCat233** [comment]
> > 不是假墙 是域名被锁+污染了
> > 只能说，你自己不会玩而已。。
> > ![image](https://private-user-images.githubusercontent.com/47879885/320279695-36041241-9181-4b2c-89f4-3ac4ee0a2b2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzA0MDMsIm5iZiI6MTcxMjY3MDEwMywicGF0aCI6Ii80Nzg3OTg4NS8zMjAyNzk2OTUtMzYwNDEyNDEtOTE4MS00YjJjLTg5ZjQtM2FjNGVlMGEyYjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDEzNDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxODUwMGFhM2RkZjg2ZGM3Mjk3ZTQ4YWIyM2MyY2QxMGRhMjY4MzgzZWNhODUzZTUxZTkxYTk5YmYyZmM5ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cwkf8hH1lYvpNQVh92iHSGz0vhMG06kIWttOjcLjwF8)

这本来就是情况不同复现不同的东西，能怎么整

**Comment by NikoCat233** [comment]
你可以试试share一下域名看多久弄墙

**Comment by mm350** [comment]
> 本人使用该项目搭建的站点只给了3-5个人用，没有上过搜索聊天，1个礼拜吃墙了
> 
> 听说更换主题能改善v2board被墙的问题，但是我更换了几个主题都不怎么支持hysteria，没有该项目默认主题适配的好。
> 
> 请问能给出抵抗秒墙的建议吗，或者说能不能添加一个给用户前端路径分流的功能，谢谢！

墙的https吧，我的同样情况换成http就好了，但是好景不长，我有换成ip登录了，快一年没问题
