### ISSUE TITLE
[BUG]PHP83在执行PHP命令时提示Using ${var} in strings is deprecated语法废弃的问题

### ISSUE THREAD

**Issue by forjustice** [wyx2685/v2board#89]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.5.2685

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
PHP83在执行PHP命令时提示Using ${var} in strings is deprecated语法废弃的问题

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
请见贴图。
<img width="659" alt="PHP83语法问题" src="https://github.com/wyx2685/v2board/assets/11565020/4d4cde80-1523-4cc7-ae3d-6f963189e587">

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by wyx2685** [comment]
废弃暂时还可以使用，不修改
