### ISSUE TITLE
原版迁移

### ISSUE THREAD

**Issue by jiayihello** [wyx2685/v2board#9]
请问如何从官方v2b迁移到这个项目

**Comment by wyx2685** [comment]
./update_dev.sh
然后全覆盖

**Comment by redtime1213** [comment]
> ./update_dev.sh 然后全覆盖
更新到dev 再下载你的所有文件完全覆盖？后续每次更新也是吗？能简单在README出个教程吗

**Comment by wyx2685** [comment]
git remote set-url origin https://github.com/wyx2685/v2board
./update.sh

**Comment by redtime1213** [comment]
> git remote set-url origin https://github.com/wyx2685/v2board git checkout master ./update.sh

谢谢 不用升级dev这么直接更新就是吧？

**Comment by wyx2685** [comment]
@redtime1213 对

**Comment by jinwyp** [comment]
从原版按照上面的步骤 升级后 网站打不开了 页面没有反应
应该如何排查呢？

**Comment by wyx2685** [comment]
@jinwyp 后台再保存一下主题设置

**Comment by jinwyp** [comment]
> @jinwyp 后台再保存一下主题设置

打不开后台管理页面啊  
lavavel 框架怎么能看到PHP 出错的日志？

**Comment by waxi-i** [comment]
1.6.0版本能直接升级吗
