### ISSUE TITLE
[Feature request]请求适配MySQL 8版本

### ISSUE THREAD

**Issue by forjustice** [wyx2685/v2board#90]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。
经测试，20240405 master分支版本不支持MySQL 8，登入时报login 500错误。但切换回MySQL 5.7则正常。

请求适配MySQL 8版本，谢谢。
祝生活愉快！

**Comment by wyx2685** [comment]
@forjustice 不会主动适配，有人PR就合
