### ISSUE TITLE
[BUG]后端在线用户上报问题反馈

### ISSUE THREAD

**Issue by zhaozongwen** [wyx2685/v2board#92]
The V2Board version number you are using
当前使用的V2Board版本号
--------
wyx2685_V1.7.5

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
拉取最新commits后，后端无法上报在线用户数，但是正常获取在线用户数
使用的后端也是wyx2685佬的xrayr最新修改版
看后端日志，没有拉取更新前正常上报，拉取后就没有上报了

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
time="2024-04-08T11:51:04-04:00" level=info msg="Total 1 online users, 0 Reported" func="github.com/wyx2685/XrayR/service/controller.(*Controller).userInfoMonitor" file="github.com/wyx2685/XrayR/service/controller/controller.go:608"

**Comment by wyx2685** [comment]
你再想想
