### ISSUE TITLE
在配置主题时报错

### ISSUE THREAD

**Issue by Chenguo886** [wyx2685/v2board#97]
将主题文件放入 /public/theme 之后进入配置界面首先提示初始化失败 之后网站无法打开 网站已打码

Warning: is_dir(): open_basedir restriction in effect. File(/sys) is not within the allowed path(s): (/www/wwwroot/***.chenguo***.xyz/:/tmp/) in /www/wwwroot/***.chenguo***.xyz/vendor/linfo/linfo/src/Linfo/OS/Linux.php on line 65

Fatal error: Uncaught RuntimeException: A facade root has not been set. in /www/wwwroot/***.chenguo***.xyz/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:258 Stack trace: #0 /www/wwwroot/***.chenguo***.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(18): Illuminate\Support\Facades\Facade::__callStatic() #1 /www/wwwroot/***.chenguo***.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(598): Illuminate\Foundation\Exceptions\RegisterErrorViewPaths->__invoke() #2 /www/wwwroot/Airport.chenguo886.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(579): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths() #3 /www/wwwroot/***.chenguo***.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(490): Illuminate\Foundation\Exceptions\Handler->renderHttpException() #4 /www/wwwroot/***.chenguo***.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Ha in /www/wwwroot/***.chenguo***.xyz/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 258

**Comment by wyx2685** [comment]
@Chenguo886 宝塔关闭防跨站

**Comment by Chenguo886** [comment]
关了之后还是这样

**Comment by Chenguo886** [comment]
ok了感谢大佬
