### ISSUE TITLE
[BUG] Failure to display the number of active devices in the node

### ISSUE THREAD

**Issue by chrikman2** [wyx2685/v2board#98]
When two nodes with the same protocol are created in the same domain (or a subdomain), only one of the nodes is active and shows the number of active devices, the other node is ready, this node still works correctly. And if you work with it, the usage volume is applied to the subscription link, but it doesn't display the number of active devices on the node.(Both nodes are connected to the same server)
![Capture](https://github.com/wyx2685/v2board/assets/167719429/352a2906-0de3-4799-b37a-f04c65f5e932)

**Comment by wyx2685** [comment]
无进展，无相同反馈，关闭
